### ISSUE TITLE
CodePen: 'pobem' is not a valid postcss plugin

### ISSUE THREAD

**Issue by ilyar** [bem-contrib/pobem#5]
I think that the reason is that the plug-in does not correspond to the manual and is absent in the plug-in repository.

## Setup
CSS Preprocessor: PostCSS http://codepen.io/ilyar/pen/dvJVaa
## Actual result
http://codepen.io/ilyar/pen/dvJVaa.css
```css
@use pobem;

:block(block)
{
   color: #0f0;
}
// 'pobem' is not a valid postcss plugin.
```
## Expected Result
```css
.block
{
   color: #0f0;
}
```
https://github.com/rebem/css/issues/5
