### ISSUE TITLE
Musings... New syntax

### ISSUE THREAD

**Issue by belozer** [bem-contrib/pobem#8]
Current favorite

№1 https://github.com/bem-contrib/pobem/issues/8#issuecomment-408677467

**Comment by belozer** [comment]
```css
@b button { /* 1 */
    @m [mod=val] {  /* 2 */
        color: #444223;
    }

    @e elem {  /* 3 */
        width: 100px;

        @m [mod=val] {  /* 4 */
            width: 40px;
        }
    }

    > h2 { /* 5 */
        opacity: .3;
    }
}
```

```css
@b button @e elem @m [mod=val] {}
```

**Comment by belozer** [comment]
```css
b-button { /* 1 */
    m-mod[val] {  /* 2 */
        color: #444223;
    }

    e-elem {  /* 3 */
        width: 100px;

        m-mod[val] {  /* 4 */
            width: 40px;
        }
    }

    > h2 { /* 5 */
        opacity: .3;
    }
}
```

```css
b-button e-elem m-mod[val] {}
```

**Comment by belozer** [comment]
```css
b:button { /* 1 */
    m:[mod=val] {  /* 2 */
        color: #444223;
    }

    e:elem {  /* 3 */
        width: 100px;

        m:[mod=val] {  /* 4 */
            width: 40px;
        }
    }

    > h2 { /* 5 */
        opacity: .3;
    }
}
```

```css
b:button e:elem m:[mod=val] {}
```

Multiple vals

```css
b:button m:[mod=val|val2|val3] e:elem  {}

.button_mod_val .button__elem,
.button_mod_val2 .button__elem,
.button_mod_val3 .button__elem { }
```

**Comment by ilyar** [comment]
Не понятно какую проблему решет этот тикет.

**Comment by belozer** [comment]
@ilyar размышления на синтаксисом.

**Comment by belozer** [comment]
@ilyar можешь потестить эти варианты по этой проблеме https://github.com/bem-contrib/pobem/issues/6?

**Comment by belozer** [comment]
```
block                 - block
:elem                 - elem name
:(mod val|val2|val3)  - mods
!                     - as is... Example - tags.
```

```css
button { /* 1 */
    :(mod val) {  /* 2 */
        color: #444223;
    }

    :elem {  /* 3 */
        width: 100px;

        :(mod val) {  /* 4 */
            width: 40px;
        }
    }

    > ! h2 { /* 5 */ 
        opacity: .3;
    }
}
```

```css
button:(mod val|val2|val3) :elem  {}

.button_mod_val .button__elem,
.button_mod_val2 .button__elem,
.button_mod_val3 .button__elem { }
```

**Comment by belozer** [comment]
```
.block                - block
elem                  - elem name
:(mod val|val2|val3)  - mods
!                     - as is... Example - tags.
```

```css
.button { /* 1 */
    :(mod val) {  /* 2 */
        color: #444223;
    }

    elem {  /* 3 */
        width: 100px;

        :(mod val) {  /* 4 */
            width: 40px;
        }
    }

    > ! h2 { /* 5 */ 
        opacity: .3;
    }
}
```

```css
.button:(mod val|val2|val3) elem  {}

.button_mod_val .button__elem,
.button_mod_val2 .button__elem,
.button_mod_val3 .button__elem { }
```
